#!/usr/bin/python
# # # # # # # # # # # # # # # # # # # # # # 
#
# project: Smart Bus Stops Done Dirt Cheap
# file: configuration.py
# description: settings core program for SBSDC
# language: python
# 
# authors: Anders Finn (anders@visiblethinking.com)
# date: 9/12/2012
# version: 1.0.0
# notes: all known configuation vars
#
# # # # # # # # # # # # # # # # # # # # # #

# TCP/IP hostname and port server listens for incomming Twilio sms messages on
HOSTNAME=visiblethinking.com
PORT=13208
LOGFILE=/var/www/smartbusstop.com/logs/sbsdc.log

# Natural language processing allows a more robust and error handled
# input however requires nltk to be installed. http://nltk.org/
NATURAL LANGUAGE=OFF
